git status
git push origin
git status
git commit -m "DM modification"
git status
git push origin
gitk --all
gitk --all
git status
git checkout -b "Ticket#2595-Testing"
git status
git add -u
git status
git commit -m "Test mods complete"
git status
git clean -fd
git status
git checkout master
git svn rebase
git checkout -b "Ticket#2595"
git status
git add
git add .
git commit -m "Modification on screen flow sheet."
git status
git push
git status
git status
gitk --all
gitk --all &
git checkout Ticket#2595-Testing
git checkout master
git checkout Ticket#2595
git checkout msater
gitk --all
git status
git add .
git commit -m "FAP Modification sheet and Autogenerate Sheet modification"
git push
git status
git add .
git commit -m "Modification based on review commmets."
git push
gitk --all
git status
cd ../../../
git status
cd ../../
git status
git status
git add .
git commit -m "Modification based on review commmets."
git push
git status
git add .
git commit -m "Modified FAP Modification sheet and Autogenerated sheet"
git push
git status
gitk --all
git status
git add -u
git status
git add Jikki/DK1/ATM/Kiosk/SPL/
git status
git add Prg/KIOSK/SPL/Statistics/
git status
git status
git commit -m "Initial commit"
git satatus
git status
gitk --all
gitk --all &
git checkout master
git svn rebase
git fetch --all
git pull
git status
git svn rebase
git checkout Ticket#2595
git status
git branch
git status
git status
git status
git merge master
git status
git fetch master
git fetch origin
gitk
gitk &
git fetch
git pull
git fetch master
git fetch origin
git checkout master
git pull Ticket#2595
git fetch Ticket#2595
git merge Ticket#2595
git status
git add Jikki/DK1/ATM/\@\@PLABEL.DT2 
got add Prg/_config_file/Dk1/atm/\@\@PLABEL.DT2 
git add Prg/_config_file/Dk1/atm/\@\@PLABEL.DT2 
git status
git gui
git status
gitk --all
gitk --all &
git checkout Ticket#2595
git checkout master
git status
git checkout Ticket#2595
git gui
git gui &
git status
git add Prg/_config_file/Dk1/atm/\@\@PLABEL.DT2 
gitk --all &
git status
git push --set-upstream origin Ticket#2595
ggit status
git status
git status
git status
gitk --all
gitk --all &
git status
git add User/BDO/EUT/Cheque_PB_Support/Passbook_SP_Setting_Temp/EUT_Setting.ini 
git status
git commit -m "EUT modification for DDC.ini"
git add 
git status
git push origin
git status
git status
gitk --all &
git checkout master
git status
git svn rebase
git status
git checkout Ticket#2595
git pull master
git fetch master
git pull origin master
git status
git status
git commit
git status
git gui
git gui &
git add Jikki/DK1/ATM/\@\@PLABEL.DT2 
git add Prg/_config_file/Dk1/atm/\@\@PLABEL.DT2 
git status
git status
git status
git push origin
git status
git status
gitk --all &
git checkout master
git status
git svn rebase
git status
git checkout Ticket#2595
git status
git merge origin
git pull origin
git merge origin
git fetch origin
git pull origin master
git merge origin/master
git status
git status
git status
git branch
git merge master
git status
git merge --abort
git status
git merge master
git status
git status
git add Jikki/DK1/ATM/\@\@PLABEL.DT2 
git add prg/_config_file/Dk1/atm/\@\@PLABEL.DT2 
git status
git status
git add prg/_config_file/Dk1/atm/\@\@PLABEL.DT2 
git status
git add Prg/_config_file/Dk1/atm/\@\@PLABEL.DT2 
git status
git gui
git status
git gui
git push origin
git status
git status
git gui &
git status
git push origin
git status
git pull
git stattus
git status
git merge --abort
git status
gitstatus
git status
git status
git gui
git status
git push
git checkout master
ig tstatus
git status
git push origin
git push
git gui
git push --set-upstream origin master
git status
git checkout Ticket#2595
ping google.com -t
gitk --all
git status
git add -u
git status
git commit -m "Modification based on review comments."
git status
git push
git status
git status
git add -u
git status
git commit -m "Modification based on review comments."
git push
git status
git status
git gui
git status
git push
git status
git add -u
git status
git commit -m "Modification based on review comments."
git status
git push
git status
git add (PHL-BDO)Ticket#2595-UM_Passbook_Counter_DM_R00.xlsx
git add /(PHL-BDO)Ticket#2595-UM_Passbook_Counter_DM_R00.xlsx
git gui
git status
git commit -m "Renamed DM document"
git push
git status
git status
git status
git add .
git commit -m "DDCCOMMON Initial commit"
git checkout master
git svn rebase
node nodeServer.js 
npm install http-proxy https fs
npm node install
npm install
node
nodeServer.js
nodeServer
git status
git add .
git commit -m "Fix on English.vbs"
git status
git checkout master
git svn rebase
git checkout -b "Ticket#2595-PG"
gitk --all
git status
git status
git status
git add .
git status
git status
git add -u
git status
git commit -m "PB Counters initial commit."
git status
git push --set-upstream origin
git push --set-upstream origin Ticket#2595-PG 
git checkout master
git svn rebase
git status
gitk --al
gitk --all
gitk --all &
git status
git push 
git status
git checkout Ticket#2595-PG
git status
git add
git add .
git commit -m "PB Counters initial commit."
git push
oh-my-posh font install
oh-my-posh font install meslo
eval "$(oh-my-posh init bash)"
exec bash
exec bash
exec bash
eval "$(oh-my-posh init bash)"
df
git checkout -b "Ticket#2595-PG"
git status
git status
git add .
git add .
git status
git status
git add .
git commit -m "PB Counters initial commit."
git push --set-upstream origin Ticket#2595-PG
git status
gitk --all &
git checkout master
git push
git push --set-upstream origin master
oh-my-posh get shell
~./profile
~/.bashrc
~/.bash_profile
~/.config
 .bash_profile 
~/ .bash_profile 
~/.bashrc
cd /.bash_profile
nano ~/.bash_profile
nano ~/.bashrc
nano ~/.profile
nano ~/.bashrc
exec bash
nano ~/.profile
nano ~/.bash_profile
exec bsah
cls
exec bash
clear
clear
Get-PoshThemes
--config 'C:/Users/Posh/jandedobbeleer.omp.json'
--config 'https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/jandedobbeleer.omp.json'
eval "$(oh-my-posh init bash --config ~/jandedobbeleer.omp.json)"
winget install JanDeDobbeleer.OhMyPosh -s winget
$env:Path += ";C:\Users\user\AppData\Local\Programs\oh-my-posh\bin"
eval "$(oh-my-posh init bash --config ~/jandedobbeleer.omp.json)"
clear
eval "$(oh-my-posh init bash --config ~/jandedobbeleer.omp.json)"
eval "$(oh-my-posh init bash --config ~/agnosterplus.omp.json)"
eval "$(oh-my-posh init bash --config ~/agnosterplus.omp.json)"
exec bash
eval "$(oh-my-posh init bash --config ~/agnosterplus.omp.json)"
eval "$(oh-my-posh init bash --config ~/agnosterplus.omp.json)"
nano ~/.bash_profile
eval "$(oh-my-posh init bash)"
exec bsah
exec bash
exec bash
eval "$(oh-my-posh init bash --config ~/craver.omp.json)"
eval "$(oh-my-posh init b
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/craver.omp.json)"

eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/jandedobbeleer.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/agnosterplus.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/atomoc.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/atomic.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/atomicbit.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/blueish.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/bubbles.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/bubblesline.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/cert.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/craver.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/lightgreen.omp.json)"
nano ~./profile
nano ~./bash_profile
nano ~/.bash_profile
nano ~/.bash_profile
exec bash
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/craver.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/cert.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/lightgreen.omp.json)"
git branch
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/night-owl.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/plague.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/bluish.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/blueish.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/velvet.omp.json)"
clear
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/craver.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/atomic.omp.json)"
git status
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/lightgreen.omp.json)"
clera
clear
git status
git branch
git checkout master
git checkout Ticket#2595
git checkout Ticket#2595-PG
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/mt.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/night-owl.omp.json)"
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/craver.omp.json)"
nano ~/.bash_profile
nano ~/.bashrc
nano ~/.profile
exec bash
eval "$(oh-my-posh init bash --config ~/Appdata/Local/Programs/oh-my-posh/themes/blueish.omp.json)"
exec bash
exec bash
clear
ping google.com
source /usr/share/git/completion/git-completion.bash
echo $SHELL
nano ~./bash_profile
nano ~./bashrc
nano ~./profile
nano ~/.profile
nano ~/.bash_profile
source ~/.bash_profile
nano ~/.bash_profile
exec bash
git status
git status
git checkout master
git checkout -b "Ticket#2595-PCL"
git status
git add .
git status
git add .
git status
git commit -m "Initial commit"
git push --set-upstream origin Ticket#2595-PCL 
nanoe ~/.profile
namp ~/.bash_profile
nano ~/.bash_profile
find / -name "bash_completion" 2>/dev/null
curl -o ~/.bash_completion https://raw.githubusercontent.com/scop/bash-completion/master/bash_completion
find / -name "bash_completion" 2>/dev/null
nano ~/bash_profile
nano ~/.bash_profile
source ~/.bash_profile
nano ~/.bash_profile
nano ~/.bash_profile
echo "source ~/.git-completion.bash" >> ~/.bash_profile
nano ~/.bash_profile
source ~/.bash_profile
nano ~/.bash_profile
source ~/.bash_profile
nano ~/.bash_profile
source ~/.bash_profile
nano ~/.bash_completion
find / -name "bash_completion" 2>/dev/null
git checkout Ticket#2595-PG
gitk --all
gitk --all &
git status
git add -u
git commit -m "Reverted other .lib files aside from Tlses.lib"
git status
git push
git status
git status
git add -u
git commit -m "Added PB counters to Clear All CTR receipt and Print All CTR receipt."
git push
git status
git checkout master
git svn rebase
gitk --all &
git checkout Ticket#2595-PG
git merge master
git status
git gui &
git push
git status
git gui
git status
ggit status
git status
git push 
git status
git status
git checkout master
git status
git status
gitk --all
gitk --all &
git status
git svn rebase
git push
git status
git checkout Ticket#2595-PG
git merge master
git merge -abort
git merge --abort
git merge master
